title:       "Shane Dickens â€“ PhD Researcher"
description: "Personal website for Shane Dickens, PhD student in Reinforcement Learning"
url:         "https://sdcoded.github.io"
baseurl:     ""

theme: al-folio

header_pages:
  - index.md
  - about.md
  - contact.md

author:
  name:  "Shane Dickens"
  email: "sard20@bath.ac.uk"
